### ISSUE TITLE
When editing in super menu customizer, clicks refresh the preview, not changes

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#145]
If all I do is click on something inside the editing area, it refreshes the preview. Ideally, it would only refresh if a change is made.

**Comment by joelworsham** [comment]
I don't follow what's happening. Can you be a bit more specific?

**Comment by brashrebel** [comment]
When you click and drag something as expected, it refreshes the preview. However, if you mouse over something in the customizer pane and click on anything at all, even if the click does not result in a change, the preview refreshes.

**Comment by joelworsham** [comment]
Yeah that isn't right... hmm I will look into it.

**Comment by joelworsham** [comment]
The reason was that the items are sortable, even when expanded. So clicking on them, even for a second, began the sorting process, and thus the preview refreshed. No bueno.

I added a 50ms delay to clicking and dragging. I believe this is small enough so it doesn't make dragging cumbersome but also enough to ignore clicks.

Let me know your thoughts.
