### ISSUE TITLE
Php error in class-clientdash-modify.php

### ISSUE THREAD

**Issue by Stevemoretz** [realbigplugins/client-dash#186]
Hi this is the complete error : 
`Notice: Undefined index: link in .../wordpress/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 292`
It is shown at the top of the menus.

**Comment by joelyoder** [comment]
I just encountered this error in the preview windows as well after moving a menu item on my testbench:
![image](https://user-images.githubusercontent.com/6054295/127931541-832b8998-07a5-4d70-b72c-a41ca3239535.png)

**Comment by joelyoder** [comment]
This issue persists after saving and refreshing the editor and throughout the entire admin side of WP. This is a critical bug we need to fix asap.

**Comment by joelyoder** [comment]
Ok, so I was able to reproduce the issue, this was being caused by the LearnDash menu in my case. The forth item in the `$submenu_item` array did not exist in the submenu.

At least this issue is not a WordPress-wide issue, but we definitely need to review the code in `class-clientdash-modify.php` because this check _should_ be preventing this error, as best as I can tell: https://github.com/realbigplugins/client-dash/blob/master/core/class-clientdash-modify.php#L247

**Comment by d4mation** [comment]
I think the issue you encountered may be a bit different, @joelyoder. 

Yours seems to be that the `$submenu_item` variable has unexpected indices in the case of the LearnDash LMS Parent Menu Item. `array_pad()` only checks for the _length_ of the Array rather than the indices that exist, which is why it didn't prevent this issue.

![image](https://user-images.githubusercontent.com/7770631/171912922-9c95e148-11e0-43e0-b557-566db48aefa9.png)

I've put a check in to ensure that an appropriate default is chosen in these cases.

@Stevemoretz 's issue appears to have been related to the Custom Link functionality. Namely, if a link wasn't entered for the Custom Link it could result in an error. I've put in a check to prevent this issue as well.

Both of these fixes should get pushed as a new version early next week.
