### ISSUE TITLE
Support Tickets extension

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#95]
We've discussed this quite a bit in the past and I still believe that a Support Tickets feature would be incredibly powerful. This is something we need for our own business. Here's a potential route we could take for the main page which lists the tickets (probably a Tickets tab on the Help page):
![support-tickets](https://cloud.githubusercontent.com/assets/4993131/4720619/59c5bcbc-5932-11e4-8d92-8d7cc31e61a4.png)

The next step would be to design the edit screen for submitting and replying to tickets.

**Comment by brandonecarr** [comment]
I have succeeded in integrating a ticketing system. Using Client Dash, Contact Form 7, Divi 2.0 CSS, and an Iframe pulling data from our home site, I've integrated the following. I took it a step further from there. We use activeCollab as a client/project management system, and that system comes in with an email filter. Anytime an email comes in with, say, "Client #1 Support", that email is filtered to create a task for Client #1. Then, notifications are pushed out to all developers, admins, etc assigned to that client/project. Very clean. And since we're using an iFrame, we only have to edit the support data in one place and it updates across the board in all installs of Client Dash. 

Furthermore, just want to say thanks for all of your hard work in developing such an awesome and modern plugin for WordPress. We absolutely love working with it, and look forward to future development! 

![openaticket1](https://cloud.githubusercontent.com/assets/5378673/6489590/4d11befe-c254-11e4-9e66-965a97675dbb.png)
![openaticket2](https://cloud.githubusercontent.com/assets/5378673/6489591/4d2a520c-c254-11e4-9f90-bab89e46fb27.png)
![openaticket3](https://cloud.githubusercontent.com/assets/5378673/6489592/4d3755e2-c254-11e4-9191-428b4ea06174.png)

**Comment by brashrebel** [comment]
@brandonecarr this is amazing! Thank you so much for sharing. Is any of this open sourced by chance? Curious to see what you did to make all this awesomeness possible.

And thank you very much for your compliment about the plugin. It is really nice to hear that you find it useful and are really utilizing it so completely and uniquely.

**Comment by brandonecarr** [comment]
To give you a basic breakdown, our site is http://dispensarypros.com. I created a page: http://dispensarypros.com/bolt-party-bus-open-a-ticket/. We use the Divi theme from Elegant Themes. They provide a template page called "Blank Page". I went in and modified the template to incorporate the CSS of the Divi contact form:

    <?php
    /*
    Template Name: Client Open A Ticket
    */
    
    get_header();
    
    $is_page_builder_used = et_pb_is_pagebuilder_used( get_the_ID() ); ?>
    
    <div id="main-content">
    
    <link rel="shortcut icon" href="http://design1.dispensarypros.com/wp-content/uploads/2014/11/logoinitials-295x300.png" /><style type="text/css" media="print">#wpadminbar { display:none; }</style>
    
    <style type="text/css" id="et-custom-css">
    body {
    background-color: #F1F1F1 !important;
    }
    .container {
    text-align: center !important;
    }
    #main-content .container {
    background-color: #F1F1F1 !important;
    }
    #main-content, .et_pb_section {
    background-color: #F1F1F1 !important;
    }
    .wpcf7-text, .wpcf7-textarea, .wpcf7-captchar {
    background-color: #fff !important;
    border: none !important;
    width: 100% !important;
    -moz-border-radius: 0 !important;
    -webkit-border-radius: 0 !important;
    border-radius: 0 !important;
    font-size: 14px;
    color: #999 !important;
    padding: 16px !important;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    }
    select.wpcf7-form-control.wpcf7-select.wpcf7-validates-as-required {
    height: 49px !important;
    width: 100% !important;
    font-size: 14px !important;
    color: #999 !important;
    background-color: #fff !important;
    }
    .wpcf7-submit {
    float: left;
    color: #2EA3F2 !important;
    margin: 8px auto 0;
    cursor: pointer;
    font-size: 20px;
    font-weight: 500;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    padding: 6px 20px;
    line-height: 1.7em;
    background: transparent;
    border: 2px solid;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -moz-transition: all 0.2s;
    -webkit-transition: all 0.2s;
    transition: all 0.2s;
    }
    .wpcf7-submit:hover { 
    background-color: #eee; 
    border-color:#eee; 
    padding: 6px 20px !important; 
    }
    .div.wpcf7-validation-errors {
    margin-top: 55px;
    }
    </style>
    
    <?php if ( ! $is_page_builder_used ) : ?>
    
    	<div class="container">
    		<div id="content-area" class="clearfix">
    			<div id="left-area">
    
    <?php endif; ?>
    
    			<?php while ( have_posts() ) : the_post(); ?>
    
    				<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
    
    				<?php if ( ! $is_page_builder_used ) : ?>
    
    				<?php
    					$thumb = '';
    
    					$width = (int) apply_filters( 'et_pb_index_blog_image_width', 1080 );
    
    					$height = (int) apply_filters( 'et_pb_index_blog_image_height', 675 );
    					$classtext = 'et_featured_image';
    					$titletext = get_the_title();
    					$thumbnail = get_thumbnail( $width, $height, $classtext, $titletext, $titletext, false, 'Blogimage' );
    					$thumb = $thumbnail["thumb"];
    
    					if ( 'on' === et_get_option( 'divi_page_thumbnails', 'false' ) && '' !== $thumb )
    						print_thumbnail( $thumb, $thumbnail["use_timthumb"], $titletext, $width, $height );
    				?>
    
    				<?php endif; ?>
    
    					<div class="entry-content">
    					<?php
    						the_content();
    
    						if ( ! $is_page_builder_used )
    							wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'Divi' ), 'after' => '</div>' ) );
    					?>
    					</div> 
    
    				<?php
    					if ( ! $is_page_builder_used && comments_open() && 'on' === et_get_option( 'divi_show_pagescomments', 'false' ) ) comments_template( '', true );
    				?>
    
    				</article> 
    
    			<?php endwhile; ?>
    
    <?php if ( ! $is_page_builder_used ) : ?>
    
    			</div> 
    
    			<?php get_sidebar(); ?>
    		</div> 
    	</div> 
    
    <?php endif; ?>
    
    </div> 
    
    <?php get_footer(); ?>

From there, I modified some background colors on that specific page to match the backgrounds of the admin page it was being displayed on. After that, I simply used:

    <iframe src ="http://dispensarypros.com/bolt-party-bus-open-a-ticket/" width="100%" height="700">
    <p>Unfortunately, your browser doesn't allow for this form. Please email us directly at bcarr@dispensarypros.com</p>
    </iframe>

on the Webmaster tab of Client Dash. Now, all I need to do is create a new contact form in Contact Form 7 sending to support@dispensarypros.com with that client's name in the subject line to filter, and create a new page for that client so that I can add that specific contact form in. All i have to do is select the page template, and I achieve that look on each client's dashboard. 

As far as being open sourced, The only code I used that wasn't mine was the CSS for the contact form, which can be modified into anything with ease. The basic functionality is all in Contact Form 7, and Contact Form 7, I believe, is open source. I'd be happy to give you access to check it out first hand if you can draw inspiration from it. Let me know, and thanks again! 

Brandon

**Comment by brashrebel** [comment]
This is remarkable @brandonecarr. I applaud you for figuring out such a creative solution. This use case is definitely inspiring some ideas for improving Client Dash and making things like this even easier.

Again, thanks for sharing this. If you have any more ideas please feel free to share them here. Also, do you mind if we ping you on similar issues just to get more input? Thanks!

**Comment by brandonecarr** [comment]
@brashrebel Thanks! I do appreciate the compliments. You guys did all the hard work, I just added a little something extra. 

I wouldn't mind at all. Please feel free to ping me anytime with anything. Thanks, and have a great day! 

Brandon

**Comment by joelworsham** [comment]
I don't think this should be a CD thing. Sounds like a potential standalone sytem.
